export const data = JSON.parse("{\"key\":\"v-77a7f758\",\"path\":\"/src/zh/posts/acm/si-wei.html\",\"title\":\"思维\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"思维\",\"category\":[\"algorithm\"],\"tag\":[\"技巧\"]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"1432背包again\",\"slug\":\"_1432背包again\",\"link\":\"#_1432背包again\",\"children\":[]},{\"level\":2,\"title\":\"C - Copy (hdu)\",\"slug\":\"c-copy-hdu\",\"link\":\"#c-copy-hdu\",\"children\":[]},{\"level\":2,\"title\":\"P1498 南蛮图腾\",\"slug\":\"p1498-南蛮图腾\",\"link\":\"#p1498-南蛮图腾\",\"children\":[]},{\"level\":2,\"title\":\"矩阵a乘b\",\"slug\":\"矩阵a乘b\",\"link\":\"#矩阵a乘b\",\"children\":[]},{\"level\":2,\"title\":\"A - I Count Two Three\",\"slug\":\"a-i-count-two-three\",\"link\":\"#a-i-count-two-three\",\"children\":[]},{\"level\":2,\"title\":\"C - Submask\",\"slug\":\"c-submask\",\"link\":\"#c-submask\",\"children\":[]},{\"level\":2,\"title\":\"1427: 数字转换\",\"slug\":\"_1427-数字转换\",\"link\":\"#_1427-数字转换\",\"children\":[]},{\"level\":2,\"title\":\"B - Cure\",\"slug\":\"b-cure\",\"link\":\"#b-cure\",\"children\":[]},{\"level\":2,\"title\":\"C AIR Triplet （牛客练习赛98）\",\"slug\":\"c-air-triplet-牛客练习赛98\",\"link\":\"#c-air-triplet-牛客练习赛98\",\"children\":[]},{\"level\":2,\"title\":\"P5019 [NOIP2018 提高组] 铺设道路\",\"slug\":\"p5019-noip2018-提高组-铺设道路\",\"link\":\"#p5019-noip2018-提高组-铺设道路\",\"children\":[]},{\"level\":2,\"title\":\"1424：螺旋数组\",\"slug\":\"_1424-螺旋数组\",\"link\":\"#_1424-螺旋数组\",\"children\":[]},{\"level\":2,\"title\":\"CF1648B Integral Array\",\"slug\":\"cf1648b-integral-array\",\"link\":\"#cf1648b-integral-array\",\"children\":[]},{\"level\":2,\"title\":\"矩阵快速幂\",\"slug\":\"矩阵快速幂\",\"link\":\"#矩阵快速幂\",\"children\":[]},{\"level\":2,\"title\":\"前世档案（pta）\",\"slug\":\"前世档案-pta\",\"link\":\"#前世档案-pta\",\"children\":[]},{\"level\":2,\"title\":\"倒数第N个字符串\",\"slug\":\"倒数第n个字符串\",\"link\":\"#倒数第n个字符串\",\"children\":[]},{\"level\":2,\"title\":\"F - The Best Path\",\"slug\":\"f-the-best-path\",\"link\":\"#f-the-best-path\",\"children\":[]},{\"level\":2,\"title\":\"越狱（vj）\",\"slug\":\"越狱-vj\",\"link\":\"#越狱-vj\",\"children\":[]},{\"level\":2,\"title\":\"货物摆放（蓝桥杯）\",\"slug\":\"货物摆放-蓝桥杯\",\"link\":\"#货物摆放-蓝桥杯\",\"children\":[]},{\"level\":2,\"title\":\"天梯赛座位分配\",\"slug\":\"天梯赛座位分配\",\"link\":\"#天梯赛座位分配\",\"children\":[]},{\"level\":2,\"title\":\"木棍游戏(二进制枚举）\",\"slug\":\"木棍游戏-二进制枚举\",\"link\":\"#木棍游戏-二进制枚举\",\"children\":[]},{\"level\":2,\"title\":\"C - 赛尔逵传说\",\"slug\":\"c-赛尔逵传说\",\"link\":\"#c-赛尔逵传说\",\"children\":[]},{\"level\":2,\"title\":\"海盗分赃（pta）\",\"slug\":\"海盗分赃-pta\",\"link\":\"#海盗分赃-pta\",\"children\":[]},{\"level\":2,\"title\":\"时间显示（蓝桥杯，思维）\",\"slug\":\"时间显示-蓝桥杯-思维\",\"link\":\"#时间显示-蓝桥杯-思维\",\"children\":[]},{\"level\":2,\"title\":\"整除光棍\",\"slug\":\"整除光棍\",\"link\":\"#整除光棍\",\"children\":[]}],\"git\":{},\"filePathRelative\":\"src/zh/posts/acm/si-wei.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
