export const pagesRoutes = [
  ["v-7517aed9","/src/demo/disable.html",{"title":"Disabling layout and features"},["/src/demo/disable","/src/demo/disable.md"]],
  ["v-3ba1c57c","/src/demo/encrypt.html",{"title":"Encryption Article"},["/src/demo/encrypt","/src/demo/encrypt.md"]],
  ["v-697c033c","/src/demo/markdown.html",{"title":"Markdown Enhance"},["/src/demo/markdown","/src/demo/markdown.md"]],
  ["v-71832e7c","/src/demo/page.html",{"title":"Page Config"},["/src/demo/page","/src/demo/page.md"]],
  ["v-b334c830","/src/demo/",{"title":"Features Demo"},["/src/demo/index.html","/src/demo/README.md"]],
  ["v-14f65a06","/src/zh/",{"title":"Demo Blog"},["/src/zh/index.html","/src/zh/README.md"]],
  ["v-1f4776c8","/src/zh/posts/love/main.html",{"title":"标题"},["/src/zh/posts/love/main","/src/zh/posts/love/main.md"]],
  ["v-cd74e5a6","/src/zh/posts/acm/bei-bao.html",{"title":"背包"},["/src/zh/posts/acm/bei-bao","/src/zh/posts/acm/bei-bao.md"]],
  ["v-7ca13df2","/src/zh/posts/acm/bfs.html",{"title":"bfs"},["/src/zh/posts/acm/bfs","/src/zh/posts/acm/bfs.md"]],
  ["v-6737109e","/src/zh/posts/acm/bi-ji.html",{"title":"笔记"},["/src/zh/posts/acm/bi-ji","/src/zh/posts/acm/bi-ji.md"]],
  ["v-7055bb39","/src/zh/posts/acm/bing-cha-ji.html",{"title":"并查集"},["/src/zh/posts/acm/bing-cha-ji","/src/zh/posts/acm/bing-cha-ji.md"]],
  ["v-6f4139a2","/src/zh/posts/acm/ccpc-icpc.html",{"title":"ccpc-icpc"},["/src/zh/posts/acm/ccpc-icpc","/src/zh/posts/acm/ccpc-icpc.md"]],
  ["v-67cde18e","/src/zh/posts/acm/cf.html",{"title":"cf"},["/src/zh/posts/acm/cf","/src/zh/posts/acm/cf.md"]],
  ["v-dd1c8a76","/src/zh/posts/acm/dfs.html",{"title":"dfs"},["/src/zh/posts/acm/dfs","/src/zh/posts/acm/dfs.md"]],
  ["v-120fc0b0","/src/zh/posts/acm/dp.html",{"title":"dp"},["/src/zh/posts/acm/dp","/src/zh/posts/acm/dp.md"]],
  ["v-0c4f6b2d","/src/zh/posts/acm/er-fen.html",{"title":"二分"},["/src/zh/posts/acm/er-fen","/src/zh/posts/acm/er-fen.md"]],
  ["v-48c9a64e","/src/zh/posts/acm/fei-bo-na-qi-shu-lie.html",{"title":"斐波那契数列"},["/src/zh/posts/acm/fei-bo-na-qi-shu-lie","/src/zh/posts/acm/fei-bo-na-qi-shu-lie.md"]],
  ["v-7d8b7424","/src/zh/posts/acm/gou-zao.html",{"title":"构造"},["/src/zh/posts/acm/gou-zao","/src/zh/posts/acm/gou-zao.md"]],
  ["v-cfc35eda","/src/zh/posts/acm/jie-gou-ti-pai-xu.html",{"title":"结构体排序"},["/src/zh/posts/acm/jie-gou-ti-pai-xu","/src/zh/posts/acm/jie-gou-ti-pai-xu.md"]],
  ["v-f63c4ac8","/src/zh/posts/acm/ju-zhen-kuai-su-mi.html",{"title":"矩阵快速幂"},["/src/zh/posts/acm/ju-zhen-kuai-su-mi","/src/zh/posts/acm/ju-zhen-kuai-su-mi.md"]],
  ["v-5471ec70","/src/zh/posts/acm/kmp.html",{"title":"kmp"},["/src/zh/posts/acm/kmp","/src/zh/posts/acm/kmp.md"]],
  ["v-c1e55d44","/src/zh/posts/acm/lian-biao.html",{"title":"链表"},["/src/zh/posts/acm/lian-biao","/src/zh/posts/acm/lian-biao.md"]],
  ["v-2abe9c7a","/src/zh/posts/acm/map.html",{"title":"map"},["/src/zh/posts/acm/map","/src/zh/posts/acm/map.md"]],
  ["v-b78fc216","/src/zh/posts/acm/pai-lie-shu-xue.html",{"title":"排列数学"},["/src/zh/posts/acm/pai-lie-shu-xue","/src/zh/posts/acm/pai-lie-shu-xue.md"]],
  ["v-5d9c21ac","/src/zh/posts/acm/pai-xu.html",{"title":"排序"},["/src/zh/posts/acm/pai-xu","/src/zh/posts/acm/pai-xu.md"]],
  ["v-a55b8cca","/src/zh/posts/acm/qian-zhui-he-he-cha-fen.html",{"title":"前缀和和差分"},["/src/zh/posts/acm/qian-zhui-he-he-cha-fen","/src/zh/posts/acm/qian-zhui-he-he-cha-fen.md"]],
  ["v-41c7f6c0","/src/zh/posts/acm/RMQ.html",{"title":"RMQ"},["/src/zh/posts/acm/RMQ","/src/zh/posts/acm/RMQ.md"]],
  ["v-032fd04e","/src/zh/posts/acm/shu-zhuang-shu-zu---xian-duan-shu.html",{"title":"树状数组-线段树"},["/src/zh/posts/acm/shu-zhuang-shu-zu---xian-duan-shu","/src/zh/posts/acm/shu-zhuang-shu-zu---xian-duan-shu.md"]],
  ["v-14d98396","/src/zh/posts/acm/shu.html",{"title":"树"},["/src/zh/posts/acm/shu","/src/zh/posts/acm/shu.md"]],
  ["v-77a7f758","/src/zh/posts/acm/si-wei.html",{"title":"思维"},["/src/zh/posts/acm/si-wei","/src/zh/posts/acm/si-wei.md"]],
  ["v-ff6ea5ea","/src/zh/posts/acm/stl.html",{"title":"stl"},["/src/zh/posts/acm/stl","/src/zh/posts/acm/stl.md"]],
  ["v-8dc789d4","/src/zh/posts/acm/xian-duan-shu.html",{"title":"线段树"},["/src/zh/posts/acm/xian-duan-shu","/src/zh/posts/acm/xian-duan-shu.md"]],
  ["v-87c6938e","/src/zh/posts/acm/zi-fu-chuan.html",{"title":"字符串"},["/src/zh/posts/acm/zi-fu-chuan","/src/zh/posts/acm/zi-fu-chuan.md"]],
  ["v-0a67690d","/src/zh/posts/acm/zui-duan-lu-+-zui-xiao-sheng-cheng-shu.html",{"title":"最短路+最小生成树"},["/src/zh/posts/acm/zui-duan-lu-+-zui-xiao-sheng-cheng-shu","/src/zh/posts/acm/zui-duan-lu-+-zui-xiao-sheng-cheng-shu.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
