<template><div><p>原题链接：<a href="https://ac.nowcoder.com/acm/contest/46800/E" target="_blank" rel="noopener noreferrer">https://ac.nowcoder.com/acm/contest/46800/E<ExternalLinkIcon/></a></p>
<p>题意：如果能判断两个L形的铁丝是由对称得来的就输出yes，否则输出no
思路：<br>
首先，如果AB=BC的话，旋转和对称的图形一样，所以不能判断是否是由对称得来的<br>
我们把AB变成长边，DE变成长边<br>
然后我们再看他们的叉积是否相等，如果相等说明是由旋转得到的，不相等就是由对称得到的<br>
注意会有精度的限制，看两个是不是一样我们就看他们的差的绝对值是否小于1e-9就可以了</p>
<div class="language-cpp line-numbers-mode" data-ext="cpp"><pre v-pre class="language-cpp"><code><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">include</span><span class="token string">&lt;bits/stdc++.h></span></span>
<span class="token keyword">using</span> <span class="token keyword">namespace</span> std<span class="token punctuation">;</span>

<span class="token keyword">int</span> xa<span class="token punctuation">,</span>ya<span class="token punctuation">,</span>xb<span class="token punctuation">,</span>yb<span class="token punctuation">,</span>xc<span class="token punctuation">,</span>yc<span class="token punctuation">;</span>
<span class="token keyword">double</span> xd<span class="token punctuation">,</span>yd<span class="token punctuation">,</span>xe<span class="token punctuation">,</span>ye<span class="token punctuation">,</span>xf<span class="token punctuation">,</span>yf<span class="token punctuation">;</span>
<span class="token keyword">double</span> <span class="token function">chaji1</span><span class="token punctuation">(</span><span class="token keyword">double</span> x1<span class="token punctuation">,</span><span class="token keyword">double</span> y1<span class="token punctuation">,</span><span class="token keyword">double</span> x2<span class="token punctuation">,</span><span class="token keyword">double</span> y2<span class="token punctuation">)</span><span class="token punctuation">{</span>
	<span class="token keyword">return</span> x1<span class="token operator">*</span>y2<span class="token operator">-</span>x2<span class="token operator">*</span>y1<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">int</span> <span class="token function">chaji</span><span class="token punctuation">(</span><span class="token keyword">int</span> x1<span class="token punctuation">,</span><span class="token keyword">int</span> y1<span class="token punctuation">,</span><span class="token keyword">int</span> x2<span class="token punctuation">,</span><span class="token keyword">int</span> y2<span class="token punctuation">)</span><span class="token punctuation">{</span>
	<span class="token keyword">return</span> x1<span class="token operator">*</span>y2<span class="token operator">-</span>x2<span class="token operator">*</span>y1<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">void</span> <span class="token function">sove</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
	cin<span class="token operator">>></span>xa<span class="token operator">>></span>ya<span class="token operator">>></span>xb<span class="token operator">>></span>yb<span class="token operator">>></span>xc<span class="token operator">>></span>yc<span class="token punctuation">;</span>
	cin<span class="token operator">>></span>xd<span class="token operator">>></span>yd<span class="token operator">>></span>xe<span class="token operator">>></span>ye<span class="token operator">>></span>xf<span class="token operator">>></span>yf<span class="token punctuation">;</span>
	<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">(</span>xa<span class="token operator">-</span>xb<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>xa<span class="token operator">-</span>xb<span class="token punctuation">)</span><span class="token operator">+</span><span class="token punctuation">(</span>ya<span class="token operator">-</span>yb<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>ya<span class="token operator">-</span>yb<span class="token punctuation">)</span><span class="token operator">==</span><span class="token punctuation">(</span>xb<span class="token operator">-</span>xc<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>xb<span class="token operator">-</span>xc<span class="token punctuation">)</span><span class="token operator">+</span><span class="token punctuation">(</span>yb<span class="token operator">-</span>yc<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>yb<span class="token operator">-</span>yc<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
		cout<span class="token operator">&lt;&lt;</span><span class="token string">"NO"</span><span class="token operator">&lt;&lt;</span>endl<span class="token punctuation">;</span>
		<span class="token keyword">return</span> <span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">(</span>xa<span class="token operator">-</span>xb<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>xa<span class="token operator">-</span>xb<span class="token punctuation">)</span><span class="token operator">+</span><span class="token punctuation">(</span>ya<span class="token operator">-</span>yb<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>ya<span class="token operator">-</span>yb<span class="token punctuation">)</span><span class="token operator">&lt;</span><span class="token punctuation">(</span>xb<span class="token operator">-</span>xc<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>xb<span class="token operator">-</span>xc<span class="token punctuation">)</span><span class="token operator">+</span><span class="token punctuation">(</span>yb<span class="token operator">-</span>yc<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>yb<span class="token operator">-</span>yc<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
		<span class="token function">swap</span><span class="token punctuation">(</span>xa<span class="token punctuation">,</span>xc<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token function">swap</span><span class="token punctuation">(</span>ya<span class="token punctuation">,</span>yc<span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token punctuation">(</span>xd<span class="token operator">-</span>xe<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>xd<span class="token operator">-</span>xe<span class="token punctuation">)</span><span class="token operator">+</span><span class="token punctuation">(</span>yd<span class="token operator">-</span>ye<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>yd<span class="token operator">-</span>ye<span class="token punctuation">)</span><span class="token operator">&lt;</span><span class="token punctuation">(</span>xe<span class="token operator">-</span>xf<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>xe<span class="token operator">-</span>xf<span class="token punctuation">)</span><span class="token operator">+</span><span class="token punctuation">(</span>ye<span class="token operator">-</span>yf<span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>ye<span class="token operator">-</span>yf<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
		<span class="token function">swap</span><span class="token punctuation">(</span>xd<span class="token punctuation">,</span>xf<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token function">swap</span><span class="token punctuation">(</span>yd<span class="token punctuation">,</span>yf<span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token function">fabs</span><span class="token punctuation">(</span><span class="token function">chaji</span><span class="token punctuation">(</span>xa<span class="token operator">-</span>xb<span class="token punctuation">,</span>ya<span class="token operator">-</span>yb<span class="token punctuation">,</span>xc<span class="token operator">-</span>xb<span class="token punctuation">,</span>yc<span class="token operator">-</span>yb<span class="token punctuation">)</span><span class="token operator">-</span><span class="token function">chaji1</span><span class="token punctuation">(</span>xd<span class="token operator">-</span>xe<span class="token punctuation">,</span>yd<span class="token operator">-</span>ye<span class="token punctuation">,</span>xf<span class="token operator">-</span>xe<span class="token punctuation">,</span>yf<span class="token operator">-</span>ye<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">&lt;=</span><span class="token number">1e-9</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
		cout<span class="token operator">&lt;&lt;</span><span class="token string">"NO"</span><span class="token operator">&lt;&lt;</span>endl<span class="token punctuation">;</span>
	<span class="token punctuation">}</span><span class="token keyword">else</span> cout<span class="token operator">&lt;&lt;</span><span class="token string">"YES"</span><span class="token operator">&lt;&lt;</span>endl<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
	<span class="token keyword">int</span> t<span class="token punctuation">;</span>
	cin<span class="token operator">>></span>t<span class="token punctuation">;</span>
	<span class="token keyword">while</span><span class="token punctuation">(</span>t<span class="token operator">--</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
		<span class="token function">sove</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">return</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


