export const data = JSON.parse("{\"key\":\"v-528eea3d\",\"path\":\"/algorithm/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/beibao.html\",\"title\":\"背包模型\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"背包模型\",\"description\":\"本质 从一堆物品中选，选择一些物品，使得这个选择满足某种条件，求最大值/最小值/方法数。 几种初始化 在设基本状态的时候有三种设法： 1.体积最多为j（一般的背包问题） 初始化所有值都是0，当体积的状态大于等于0的时候才能转换 2.体积恰好为j 初始化f[0]=0,其他的都是正无穷（根据题意设），当体积恰好是要求的体积且大于0的时候才能转换 3.体积最...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/algorithm/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92/beibao.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Demo\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"背包模型\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"本质 从一堆物品中选，选择一些物品，使得这个选择满足某种条件，求最大值/最小值/方法数。 几种初始化 在设基本状态的时候有三种设法： 1.体积最多为j（一般的背包问题） 初始化所有值都是0，当体积的状态大于等于0的时候才能转换 2.体积恰好为j 初始化f[0]=0,其他的都是正无穷（根据题意设），当体积恰好是要求的体积且大于0的时候才能转换 3.体积最...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"本质\",\"slug\":\"本质\",\"link\":\"#本质\",\"children\":[]},{\"level\":2,\"title\":\"几种初始化\",\"slug\":\"几种初始化\",\"link\":\"#几种初始化\",\"children\":[]},{\"level\":2,\"title\":\"01背包\",\"slug\":\"_01背包\",\"link\":\"#_01背包\",\"children\":[{\"level\":3,\"title\":\"01背包求方案数\",\"slug\":\"_01背包求方案数\",\"link\":\"#_01背包求方案数\",\"children\":[]}]},{\"level\":2,\"title\":\"完全背包\",\"slug\":\"完全背包\",\"link\":\"#完全背包\",\"children\":[{\"level\":3,\"title\":\"完全背包求方案数\",\"slug\":\"完全背包求方案数\",\"link\":\"#完全背包求方案数\",\"children\":[]}]},{\"level\":2,\"title\":\"多重背包\",\"slug\":\"多重背包\",\"link\":\"#多重背包\",\"children\":[{\"level\":3,\"title\":\"二进制优化\",\"slug\":\"二进制优化\",\"link\":\"#二进制优化\",\"children\":[]}]},{\"level\":2,\"title\":\"分组背包\",\"slug\":\"分组背包\",\"link\":\"#分组背包\",\"children\":[{\"level\":3,\"title\":\"分组背包求具体方案\",\"slug\":\"分组背包求具体方案\",\"link\":\"#分组背包求具体方案\",\"children\":[]}]},{\"level\":2,\"title\":\"有依赖的背包问题\",\"slug\":\"有依赖的背包问题\",\"link\":\"#有依赖的背包问题\",\"children\":[]},{\"level\":2,\"title\":\"二维费用的背包问题\",\"slug\":\"二维费用的背包问题\",\"link\":\"#二维费用的背包问题\",\"children\":[]},{\"level\":2,\"title\":\"货币系统\",\"slug\":\"货币系统\",\"link\":\"#货币系统\",\"children\":[]},{\"level\":2,\"title\":\"混合背包问题\",\"slug\":\"混合背包问题\",\"link\":\"#混合背包问题\",\"children\":[]},{\"level\":2,\"title\":\"背包问题求方案数\",\"slug\":\"背包问题求方案数\",\"link\":\"#背包问题求方案数\",\"children\":[]},{\"level\":2,\"title\":\"背包问题求具体方案\",\"slug\":\"背包问题求具体方案\",\"link\":\"#背包问题求具体方案\",\"children\":[]}],\"readingTime\":{\"minutes\":22.58,\"words\":6775},\"filePathRelative\":\"algorithm/动态规划/beibao.md\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
